// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ErIvvPhmfW41Yuw86pXsSl-DnOkN2CU',
    appId: '1:986490468242:web:04a8c7abbe762d57c8b34b',
    messagingSenderId: '986490468242',
    projectId: 'attendancejomngaji',
    authDomain: 'attendancejomngaji.firebaseapp.com',
    storageBucket: 'attendancejomngaji.firebasestorage.app',
    measurementId: 'G-XF36XECV62',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP9KQ94UrLBoMQOm21raaUGzyaTrhntxQ',
    appId: '1:986490468242:android:5546e0f837015a63c8b34b',
    messagingSenderId: '986490468242',
    projectId: 'attendancejomngaji',
    storageBucket: 'attendancejomngaji.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjZPZr_-4FN9OxT8-GkM_ucNbMjiogjVc',
    appId: '1:986490468242:ios:a33a0375f848d308c8b34b',
    messagingSenderId: '986490468242',
    projectId: 'attendancejomngaji',
    storageBucket: 'attendancejomngaji.firebasestorage.app',
    iosBundleId: 'com.example.attendanceMbip',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjZPZr_-4FN9OxT8-GkM_ucNbMjiogjVc',
    appId: '1:986490468242:ios:a33a0375f848d308c8b34b',
    messagingSenderId: '986490468242',
    projectId: 'attendancejomngaji',
    storageBucket: 'attendancejomngaji.firebasestorage.app',
    iosBundleId: 'com.example.attendanceMbip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9ErIvvPhmfW41Yuw86pXsSl-DnOkN2CU',
    appId: '1:986490468242:web:5e50c11c3e7a64aac8b34b',
    messagingSenderId: '986490468242',
    projectId: 'attendancejomngaji',
    authDomain: 'attendancejomngaji.firebaseapp.com',
    storageBucket: 'attendancejomngaji.firebasestorage.app',
    measurementId: 'G-578DL294BF',
  );
}
